# Generated by Django 3.2.8 on 2021-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
